from datetime import date, datetime

from university_recruitment.models import RecruitmentJob, SourceType
from university_recruitment.storage import JobStore


SAMPLE_JOBS = [
    RecruitmentJob(
        id="sample-zhongda-ai-001",
        school="中山大学",
        department="计算机学院",
        position="人工智能方向青年教师",
        discipline="计算机科学与技术、人工智能、机器学习",
        location="广州-海珠区",
        longitude=113.3014,
        latitude=23.1007,
        education_requirement="博士",
        job_type="教学科研岗",
        deadline=date(2026, 12, 31),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://rcb.sysu.edu.cn",
        published_at=date(2026, 6, 1),
        collected_at=datetime.utcnow(),
        description="中山大学计算机学院招聘人工智能方向青年教师，要求博士学历，有高水平论文优先。工作地点：广州市海珠区新港西路135号。",
    ),
    RecruitmentJob(
        id="sample-huagong-cailiao-002",
        school="华南理工大学",
        department="材料科学与工程学院",
        position="材料方向博士后",
        discipline="材料科学、先进制造、新能源材料",
        location="广州-天河区",
        longitude=113.3514,
        latitude=23.1547,
        education_requirement="博士",
        job_type="博士后",
        deadline=date(2026, 9, 30),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://www2.scut.edu.cn/hr/",
        published_at=date(2026, 5, 20),
        collected_at=datetime.utcnow(),
        description="华南理工大学材料学院招聘博士后，面向新能源材料、先进制造方向，支持科研启动经费。地址：广州市天河区五山路381号。",
    ),
    RecruitmentJob(
        id="sample-guangda-jiaoshi-003",
        school="广州大学",
        department="计算机科学与网络工程学院",
        position="网络空间安全方向教授",
        discipline="网络空间安全、计算机科学与技术",
        location="广州-番禺区",
        longitude=113.3724,
        latitude=23.0457,
        education_requirement="博士",
        job_type="教学科研岗",
        deadline=date(2027, 3, 31),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://www.gzhu.edu.cn/rczp1/gccrczpgg.htm",
        published_at=date(2026, 6, 10),
        collected_at=datetime.utcnow(),
        description="广州大学招聘网络空间安全方向教授/副教授，要求博士学位，有国家级项目经历者优先。地址：广州市番禺区大学城外环西路230号。",
    ),
    RecruitmentJob(
        id="sample-jiying-jijin-004",
        school="暨南大学",
        department="经济学院",
        position="金融学方向讲师",
        discipline="金融学、经济学",
        location="广州-天河区",
        longitude=113.3514,
        latitude=23.1291,
        education_requirement="博士",
        job_type="教学科研岗",
        deadline=date(2026, 11, 30),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://hrdam.jnu.edu.cn/",
        published_at=date(2026, 6, 5),
        collected_at=datetime.utcnow(),
        description="暨南大学经济学院招聘金融学方向讲师，博士学历，有海外留学经历者优先。地址：广州市天河区黄埔大道西601号。",
    ),
    RecruitmentJob(
        id="sample-guangwai-waiyu-005",
        school="广东外语外贸大学",
        department="英语语言文化学院",
        position="英语语言学教授",
        discipline="英语语言文学、语言学",
        location="广州-白云区",
        longitude=113.2650,
        latitude=23.1850,
        education_requirement="博士",
        job_type="教学科研岗",
        deadline=date(2026, 10, 15),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://rsc.gdufs.edu.cn/zpxx.htm",
        published_at=date(2026, 5, 15),
        collected_at=datetime.utcnow(),
        description="广东外语外贸大学招聘英语语言学教授，要求博士学历，发表过高水平论文。地址：广州市白云区白云大道北2号。",
    ),
    RecruitmentJob(
        id="sample-nanyi-yixue-006",
        school="南方医科大学",
        department="基础医学院",
        position="病理学与病理生理学教师",
        discipline="基础医学、病理学",
        location="广州-白云区",
        longitude=113.3240,
        latitude=23.1800,
        education_requirement="博士",
        job_type="教学科研岗",
        deadline=date(2026, 8, 20),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://portal.smu.edu.cn/renshi/",
        published_at=date(2026, 4, 10),
        collected_at=datetime.utcnow(),
        description="南方医科大学基础医学院招聘病理学方向教师，博士学历，有医学背景优先。地址：广州市白云区沙太南路1023号。",
    ),
    RecruitmentJob(
        id="sample-zhongyi-zhongyao-007",
        school="广州中医药大学",
        department="中药学院",
        position="中药学学科带头人",
        discipline="中药学、药学",
        location="广州-番禺区",
        longitude=113.4070,
        latitude=23.0580,
        education_requirement="博士",
        job_type="教学科研岗",
        deadline=date(2026, 7, 31),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://rsc.gzucm.edu.cn/rcyj.htm",
        published_at=date(2026, 3, 15),
        collected_at=datetime.utcnow(),
        description="广州中医药大学中药学院招聘学科带头人，博士学历，正高职称，主持过国家级科研项目。地址：广州市番禺区大学城外环东路232号。",
    ),
    RecruitmentJob(
        id="sample-tieke-jiaotong-008",
        school="广州铁路职业技术学院",
        department="机车车辆学院",
        position="轨道交通信号与控制教师",
        discipline="轨道交通、控制工程",
        location="广州-增城区",
        longitude=113.8300,
        latitude=23.2800,
        education_requirement="硕士及以上",
        job_type="教学科研岗",
        deadline=date(2026, 12, 31),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://www.gtxy.edu.cn/zzrsc/rczp/zpgg/",
        published_at=date(2026, 6, 1),
        collected_at=datetime.utcnow(),
        description="广州铁路职业技术学院招聘轨道交通方向教师，硕士及以上学历，有企业经验优先。地址：广州市增城区朱村街科德大道198号。",
    ),
    RecruitmentJob(
        id="sample-chengjian-gongcheng-009",
        school="广州城建职业学院",
        department="建筑工程学院",
        position="智能建造技术专任教师",
        discipline="土木工程、智能建造",
        location="广州-从化区",
        longitude=113.5600,
        latitude=23.5500,
        education_requirement="硕士及以上",
        job_type="教学科研岗",
        deadline=date(2026, 12, 31),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://rsw.gzccc.edu.cn/bf/xxgg/15.htm",
        published_at=date(2026, 5, 20),
        collected_at=datetime.utcnow(),
        description="广州城建职业学院招聘智能建造技术专任教师，硕士及以上学历，有建筑行业经验者优先。地址：广州市从化区环市东路166号。",
    ),
    RecruitmentJob(
        id="sample-huali-gongxue-010",
        school="广州华立学院",
        department="机电工程学院",
        position="机械设计制造及自动化教师",
        discipline="机械工程、自动化",
        location="广州-增城区",
        longitude=113.8200,
        latitude=23.2100,
        education_requirement="硕士及以上",
        job_type="教学科研岗",
        deadline=date(2027, 1, 15),
        source_type=SourceType.UNIVERSITY_TALENT_SITE,
        source_name="样本数据",
        source_url="https://www.hualixy.edu.cn/rsc/rczp1/rczp",
        published_at=date(2026, 6, 1),
        collected_at=datetime.utcnow(),
        description="广州华立学院机电工程学院招聘机械设计制造及自动化专业教师，硕士及以上学历。地址：广州市增城区华立路7号。",
    ),
]


def main() -> None:
    store = JobStore()
    store.init_db()
    count = store.upsert_jobs(SAMPLE_JOBS)
    print(f"Seeded {count} recruitment jobs.")


if __name__ == "__main__":
    main()
