"""Add media library models

Revision ID: 0012_add_media_library_models
Revises: 0011_add_restore_status_message
Create Date: 2025-08-28 04:18:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0012_add_media_library_models'
down_revision = '0011_add_restore_status_message'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create media_folders table
    op.create_table('media_folders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('visibility', sa.Enum('private', 'shared', 'public'), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['parent_id'], ['media_folders.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_folders_owner_id'), 'media_folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_folders_parent_id'), 'media_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_media_folders_visibility'), 'media_folders', ['visibility'], unique=False)
    
    # Create media table
    op.create_table('media',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('original_name', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.BigInteger(), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('media_type', sa.Enum('image', 'video', 'document', 'audio', 'other'), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('visibility', sa.Enum('private', 'shared', 'public'), nullable=False),
        sa.Column('folder_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('alt_text', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tags', mysql.LONGTEXT(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('focal_x', sa.Float(), nullable=True),
        sa.Column('focal_y', sa.Float(), nullable=True),
        sa.Column('variants', mysql.LONGTEXT(), nullable=True),
        sa.Column('download_count', sa.Integer(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['folder_id'], ['media_folders.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_file_hash'), 'media', ['file_hash'], unique=False)
    op.create_index(op.f('ix_media_file_path'), 'media', ['file_path'], unique=False)
    op.create_index(op.f('ix_media_folder_id'), 'media', ['folder_id'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_mime_type'), 'media', ['mime_type'], unique=False)
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_visibility'), 'media', ['visibility'], unique=False)
    
    # Create media_usage table
    op.create_table('media_usage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('media_id', sa.Integer(), nullable=False),
        sa.Column('usage_type', sa.Enum('article_content', 'article_featured', 'user_avatar', 'other'), nullable=False),
        sa.Column('reference_id', sa.Integer(), nullable=True),
        sa.Column('reference_type', sa.String(length=50), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_usage_media_id'), 'media_usage', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_usage_reference_id'), 'media_usage', ['reference_id'], unique=False)
    op.create_index(op.f('ix_media_usage_usage_type'), 'media_usage', ['usage_type'], unique=False)
    op.create_index(op.f('ix_media_usage_user_id'), 'media_usage', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_usage_user_id'), table_name='media_usage')
    op.drop_index(op.f('ix_media_usage_usage_type'), table_name='media_usage')
    op.drop_index(op.f('ix_media_usage_reference_id'), table_name='media_usage')
    op.drop_index(op.f('ix_media_usage_media_id'), table_name='media_usage')
    op.drop_table('media_usage')
    
    op.drop_index(op.f('ix_media_visibility'), table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_index(op.f('ix_media_mime_type'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_folder_id'), table_name='media')
    op.drop_index(op.f('ix_media_file_path'), table_name='media')
    op.drop_index(op.f('ix_media_file_hash'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_table('media')
    
    op.drop_index(op.f('ix_media_folders_visibility'), table_name='media_folders')
    op.drop_index(op.f('ix_media_folders_parent_id'), table_name='media_folders')
    op.drop_index(op.f('ix_media_folders_owner_id'), table_name='media_folders')
    op.drop_table('media_folders')
    # ### end Alembic commands ###