version: '3.9'
services:
  backend:
    build: ./backend
    container_name: blog_backend
    command: gunicorn -w 4 -k gthread --threads 4 -b 0.0.0.0:8000 app:create_app\(\)
    environment:
      DATABASE_URL: mysql+pymysql://blog:blog@db:3306/blog?charset=utf8mb4
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      MEILISEARCH_URL: http://meili:7700
      JWT_SECRET_KEY: dev-secret
      CORS_ORIGINS: "*"
      UPLOAD_DIR: /app/backend/uploads_store
      ALLOWED_IMAGE_TYPES: image/jpeg,image/png,image/webp
      MAX_IMAGE_SIZE: 5242880
    depends_on:
      - db
      - redis
      - meili
    volumes:
      - uploads:/app/backend/uploads_store
    ports:
      - "8000:8000"
  celery_worker:
    build: ./backend
    command: sh -c "flask db upgrade && celery -A app.tasks.celery_app worker -l info"
    depends_on:
      - backend
      - redis
    environment:
      DATABASE_URL: mysql+pymysql://blog:blog@db:3306/blog?charset=utf8mb4
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      MEILISEARCH_URL: http://meili:7700
      JWT_SECRET_KEY: dev-secret
      FLASK_APP: run.py
  celery_beat:
    build: ./backend
    command: sh -c "celery -A app.tasks.celery_app beat -l info"
    depends_on:
      - backend
      - redis
    environment:
      DATABASE_URL: mysql+pymysql://blog:blog@db:3306/blog?charset=utf8mb4
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      MEILISEARCH_URL: http://meili:7700
      JWT_SECRET_KEY: dev-secret
      FLASK_APP: run.py
  db:
    image: mysql:8.4
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7-alpine
  meili:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_NO_ANALYTICS: 'true'
    volumes:
      - meilidata:/meili_data
    ports:
      - "7700:7700"
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=/api/v1
    ports:
      - "5173:80"
volumes:
  mysqldata:
  meilidata:
  uploads:
